@startuml
class Person {
    +Object[] elementData
    +drink()
    #says()
    talk(String topic)
    go(String placeName)
    -internalCall(long hours)
    -validate(String fingerPrint, double time)
}

class Teacher {
    +doTeaching(int hours)
}
class Student {
    +makeDiscussion(Float timeVal)
    #connectWithOtherStudent(int millis)
    -doStuffs()
    -shave()
}
Person <|-- Teacher
Person <|-- Student

interface Discussion {
    +speak()
    +interrupt()
}


class GoodStudent implements Discussion{
    +shareKnowledge()
}
class BadStudent implements Discussion{
    +destroyFurniture()
}
Student <|-- GoodStudent
Student <|-- BadStudent

@enduml